spring.application.name=smartinternship

spring.datasource.url=jdbc:mysql://localhost:3306/miniproject

spring.datasource.username=root
spring.datasource.password=3115
spring.jpa.hibernate.ddl-auto=update

jwt.key=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5TaWduaW5nMTIzNDU2
jwt.expiration=3600000